# account phone number
account_phone: "+917598872066"

# app info
# see https://core.telegram.org/api/obtaining_api_id

api_id: 24069737
api_hash: 355c5539a2372a34ed1e42782a0669af

# parse messages delay in seconds
delay: 5

# the number of messages whose edits in the original channel will be tracked
edit_message_checker_limit: 10

# groups, maybe several
# see YAML array of object format
groups:

  # group name, can be anything
  - name: test
    # list of channels, chats or private messages from where you want to copy messages
    sources:
      # expected channel\group\dm title which is visible in the list of dialogs in your telegram application for example

      - "documentary_OTT"

    # list of channels\chats\private messages where you want to copy messages
    destinations:
      - "hitestingmychannel"

    # if not empty, only messages that contain one of the words specified in the whitelist are copied
    whitelist: [ ]
